# Configuration
@tenant = 1
@operation-id = aeeaaaaaagecovsdacc24amuol3gqtqaaaaq

### Récupère la liste des opérations en cours
GET {{url-access}}/admin-external/v1/operations
Content-Type: application/json
Accept: application/json
X-Tenant-Id: {{tenant}}

{}

### Annulation d'une opération en mode forcé
DELETE {{url-access}}/admin-external/v1/operations/{{operation-id}}
X-Force: true
Content-Type: application/json
Accept: application/json
X-Tenant-Id: {{tenant}}
