---

- name: copy temporary script to update unit schema
  template:
    src: "migrate_approximate_dates_units.js.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/tmp/mongos/migrate_approximate_dates_units.js"
    owner: "{{ vitam_defaults.users.vitamdb }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"

- name: update in mongo unit schema.
  command: "mongosh --host mongo-data-mongos.service.{{ consul_domain }} --port {{ mongodb.mongos_port }} -u {{ mongodb['mongo-data'].admin.user }} -p {{ mongodb['mongo-data'].admin.password }} --quiet --file {{ vitam_defaults.folder.root_path }}/tmp/mongos/migrate_approximate_dates_units.js"
  no_log: "{{ hide_passwords_during_deploy }}"

- name: remove temporary script.
  file:
    path: "{{ vitam_defaults.folder.root_path }}/tmp/mongos/migrate_approximate_dates_units.js"
    state: absent
