---

- name: Reset mongo server list
  set_fact:
    mongo_list: []

- name: Compute the mongo server list
  set_fact:
    mongo_list: "{{ mongo_list | default([]) + [ item ] }}"
  when: mongo_cluster_name == hostvars[item]['mongo_cluster_name']
  with_items: "{{ groups[mongo_group] }}"
