---

- name: Reset mongos server list
  set_fact:
    mongos_list: []
    mongos_nodes: []

- name: Compute the mongos server list
  set_fact:
    mongos_list: "{{ mongos_list + [ item ] }}"
  when: mongo_cluster_name == hostvars[item]['mongo_cluster_name']
  with_items: "{{ groups[mongo_group] }}"

- block:

  - name: Compute list of mongos nodes
    set_fact:
      mongos_nodes: "{{ mongos_nodes + [ hostvars[item]['ip_service'] + ':' + mongodb.mongos_port | string ] }}"
    loop: "{{ mongos_list }}"

  - name: Set mongos connection & credentials
    set_fact:
      mongos_dnsname: "{{ ip_service if inventory_hostname in single_vm_hostnames else mongo_cluster_name + '-mongos.service.' + consul_domain }}"
      mongos_connection: "mongodb://{{ mongos_nodes | join(',') }}"
      mongos_credentials: "-u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet"
    no_log: "{{ hide_passwords_during_deploy }}"

  - name: Wait for the service port to be open
    wait_for:
      host: "{{ mongos_dnsname }}"
      port: "{{ mongodb.mongos_port }}"
      timeout: "{{ vitam_defaults.services.start_timeout }}"

  - name: Copy database scripts
    copy:
      src: "{{ item }}"
      dest: "{{ vitam_defaults.folder.root_path }}/script/mongos"
      owner: "{{ vitam_defaults.users.vitamdb }}"
      group: "{{ vitam_defaults.users.group }}"
      mode: "{{ vitam_defaults.folder.conf_permission }}"
    with_items:
      - start_balancer.js
      - stop_balancer.js

  - name: Start the balancer
    command: "mongosh {{ mongos_connection }} {{ mongos_credentials }} --file {{ vitam_defaults.folder.root_path }}/script/mongos/start_balancer.js"
    no_log: "{{ hide_passwords_during_deploy }}"
    register: start_balancer
    retries: 20
    delay: 5
    until: start_balancer.rc == 0
    when: state == "started"

  - name: Stop the balancer
    command: "mongosh {{ mongos_connection }} {{ mongos_credentials }} --file {{ vitam_defaults.folder.root_path }}/script/mongos/stop_balancer.js"
    no_log: "{{ hide_passwords_during_deploy }}"
    register: stop_balancer
    retries: 20
    delay: 5
    until: stop_balancer.rc == 0
    when: state == "stopped"

  when: inventory_hostname == mongos_list | last
