---

- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "unit"
    - mapping_folder: "unit"

- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "collect_unit"
    - mapping_folder: "unit"

- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "objectgroup"
    - mapping_folder: "objectgroup"

- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "collect_objectgroup"
    - mapping_folder: "objectgroup"

- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "accesscontract"
    - mapping_folder: "accesscontract"

- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "profile"
    - mapping_folder: "profile"

- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "archiveunitprofile"
    - mapping_folder: "archiveunitprofile"


- include_tasks: list_and_migrate_alias_mapping.yml
  vars:
    - alias_prefix: "agencies"
    - mapping_folder: "agencies"
