authentication: false
jettyConfig: jetty-config.xml
authorizeTrackTotalHits : true
#Basic Authentication
adminBasicAuth:
- userName: adminUser
  password: adminPassword

ingestionThreadPoolSize: 4
ingestionThreadFrequencySeconds: 5
