urlMetadata: http://metadata.service.consul:8200/
urlMetadataCollect: http://metadata-collect.service.consul:8290/
urlWorkspace: http://workspace.service.consul:8201/
urlWorkspaceCollect: http://workspace-collect.service.consul:8291/
jettyConfig: jetty-config.xml
workflowRefreshPeriod: 1
processingCleanerPeriod: 1
maxDistributionInMemoryBufferSize: 100000
maxDistributionOnDiskBufferSize: 100000000

# Async resource monitoring config (for unavailable async resources when using tape storage offer)
delayAsyncResourceMonitor: 60
delayAsyncResourceCleaner: 60
