---

filebeat_processors:
  processors:
    - add_host_metadata:
        when.not.contains.tags: forwarded
    - add_cloud_metadata: ~
    - add_docker_metadata: ~

filebeat_log:
  level: INFO
  directory: "/vitam/log/filebeat"
  filename: filebeat.log
  keepfiles: 7

cots_list:
  - cerebro
  - grafana
  - kibana
  - prometheus
  - alertmanager
