---

- include_tasks: prometheus_blackbox_exporter_enabled.yml
  when: prometheus.blackbox_exporter.enabled | default(true) | bool == true

- include_tasks: prometheus_blackbox_exporter_disabled.yml
  when: prometheus.blackbox_exporter.enabled | default(true) | bool == false
